---
# tasks file for docker_pull

---
- name: Pull Docker image from Docker Hub
  shell: docker pull soumik1410/imagecaptioner_mt2024153:latest
  register: docker_pull_result

- name: Show Docker pull output
  debug:
    var: docker_pull_result.stdout_lines
