apiVersion: v1
kind: Service
metadata:
  name: captioner-service
  namespace: captioner-service-mt2024153
spec:
  type: NodePort
  selector:
    app: captioner
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8501
      nodePort: 30080

