apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
  namespace: image-caption-app-mt2024153
  labels:
    k8s-app: fluent-bit
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush        1
        Log_Level    info
        Parsers_File parsers.conf

    [INPUT]
        Name              tail
        Path              /var/log/containers/*.log
        Parser            docker
        Tag               kube.*
        Refresh_Interval  5
        Mem_Buf_Limit     5MB
        Skip_Long_Lines   On
        DB                /var/log/flb_kube.db

    [FILTER]
        Name                kubernetes
        Match               kube.*
        Kube_Tag_Prefix     kube.var.log.containers.
        Kube_URL            https://kubernetes.default.svc:443
        Merge_Log           On
        Keep_Log            Off
        Annotations         Off
        Labels              On
        K8S-Logging.Parser  On
        K8S-Logging.Exclude Off
    
    [FILTER]
        Name        grep
        Match       kube.*
        Regex       kubernetes.namespace_name ^image-caption-app-mt2024153$

    [OUTPUT]
        Name            loki
        Match           *
        Uri             http://loki:3100/loki/api/v1/push
        label_keys      $job,$namespace,$container_name
        remove_keys     source,stream
        auto_kubernetes_labels true

  parsers.conf: |
    [PARSER]
        Name         docker
        Format       json
        Time_Key     time
        Time_Format  %Y-%m-%dT%H:%M:%S.%L
        Time_Keep    On
        Decode_Field_As   escaped_utf8    log    do_next
        Decode_Field_As   json            log

