apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: image-caption-app-mt2024153
  labels:
    app: grafana
    grafana_datasource: "1"
data:
  loki-datasource.yaml: |
    apiVersion: 1
    datasources:
      - name: Loki
        type: loki
        access: proxy
        orgId: 1
        url: http://loki:3100
        basicAuth: false
        isDefault: true
        version: 1
        editable: true

