apiVersion: v1
kind: Service
metadata:
  name: loki
  namespace: image-caption-app-mt2024153
  labels:
    app: loki
spec:
  ports:
    - name: http
      port: 3100
      targetPort: 3100
  selector:
    app: loki

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: loki
  namespace: image-caption-app-mt2024153
  labels:
    app: loki
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loki
  template:
    metadata:
      labels:
        app: loki
    spec:
      initContainers:
      - name: init-loki-storage
        image: busybox
        command: ["sh", "-c", "mkdir -p /loki/index /loki/cache /loki/chunks /loki/compactor"]
        volumeMounts:
          - name: loki-storage
            mountPath: /loki
      containers:
        - name: loki
          image: grafana/loki:2.9.4
          ports:
            - containerPort: 3100
          args:
            - "-config.file=/etc/loki/local-config.yaml"
          volumeMounts:
            - name: config
              mountPath: /etc/loki
            - name: loki-storage
              mountPath: /loki
          securityContext:
            runAsUser: 0
      volumes:
        - name: config
          configMap:
            name: loki-config
        - name: loki-storage
          emptyDir: {}
